[package]
name = "reg_machine"
version = "0.1.0"
edition = "2018"
default-run = "fibonacci"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl-trait-for-tuples = "0.2.1"
nom = "6.2.1"
thiserror = "1.0"