[package]
name = "reg_machine"
version = "1.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl-trait-for-tuples = "0.2.1"
nom = "6.2.1"
thiserror = "1.0"